export const LANGUAGE_EN = {
  name: 'Name',
  phone: 'Phone',
  title: 'Title',
  tag: 'Tag',
  tags: 'Tags',
  language: 'Language',
  content_type: 'Content Type',
  order: 'Order',
  description: 'Description',
  content: 'Content',
  article: 'Article',
  poster: 'Poster',
  thumb: 'Thumb',
  menu: 'Menu',
  menus: 'Menus',
  body: 'Body',
  template: 'Template',
  show: 'Show',
  channel: 'Channel',
  dashboard: 'Dashboard',
  actions: 'Actions',
  add: 'Add',
  delete: 'Delete',
  edit: 'Edit',
  save: 'Save',
  Logout: 'Logout',
  icp: 'ICP',
  code_public: 'Public Code',
  code_mini: 'Mini Code',
  code_download: 'Download Code',
  none: 'None',
  custom_type: 'Custom Type',
  confirm: 'Confirm',
  cancel: 'Cancel',
  dialog_msg: 'Are you sure you want to delete this message?',
  'AiFox CMS Manage': 'AiFox CMS Manage',
  'Add Submenu': 'Add Submenu',
  'Add Article': 'Add Article',
  'View Articles': 'View Articles',
  'Content Manage': 'Content Manage',
  'System Manage': 'System Manage',
  'Menu Manage': 'Menu Manage',
  'Article Manage': 'Article Manage',
  'File Manage': 'File Manage',
  'Site Manage': 'Site Manage',
  'Default Language': 'Default Language',
  'User Info': 'User Info',
  'User Manage': 'User Manage',
  file: 'File',
  missing: 'Missing',
  back: 'Back',
  search: 'Search',
  company: 'Company',
  username: 'Username',
  email: 'Email',
  password: 'Password',
  role: 'Role',
  confirmed: 'Confirmed',
  true: 'Yes',
  false: 'No'
};
